# Docker Compose for Local Development

version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: car-rental-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: CarRentalDB
    volumes:
      - mongodb_data:/data/db
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - car-rental-network

  backend:
    build:
      context: ../../backend
      dockerfile: ../aws/docker/Dockerfile.backend
    container_name: car-rental-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - MongoDB__ConnectionString=mongodb://admin:password123@mongodb:27017/CarRentalDB?authSource=admin
      - MongoDB__DatabaseName=CarRentalDB
    depends_on:
      - mongodb
    networks:
      - car-rental-network

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../aws/docker/Dockerfile.frontend
    container_name: car-rental-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - car-rental-network

volumes:
  mongodb_data:

networks:
  car-rental-network:
    driver: bridge
